services:
  comfyui:
    image: hqtech/whalecomfy:latest
    build: .
    volumes:
      - ${CLONE_DIR}/data/models:/ComfyUI/models:rw
      - ${CLONE_DIR}/data/custom_nodes:/ComfyUI/custom_nodes:rw
      - ${CLONE_DIR}/data/venv:/ComfyUI/venv:rw
      - ${CLONE_DIR}/data/workflows:/ComfyUI/user/default/workflows:rw
    command: python /app/download_models.py
    working_dir: /ComfyUI
