services:
  comfyui:
    image: hqtech/whalecomfy:latest
    platform: linux/arm64 
    build:
      context: .
      dockerfile: Dockerfile.mac
    volumes:
      - ${CLONE_DIR}/data/models:/ComfyUI/models:rw
      - ${CLONE_DIR}/data/custom_nodes:/ComfyUI/custom_nodes:rw
      - ${CLONE_DIR}/data/venv:/ComfyUI/venv:rw
      - ${CLONE_DIR}/data/workflows:/ComfyUI/user/default/workflows:rw
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - GPU_ENABLED=true
      - PYTHONUNBUFFERED=1
    ports:
      - ${server_port}:8188
    stop_signal: SIGKILL
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
