services:
  comfyui:
    image: hqtech/whalecomfy:latest
    build: .
    volumes:
      - ${CLONE_DIR}/models:/ComfyUI/models:rw
      - ${CLONE_DIR}/custom_nodes:/ComfyUI/custom_nodes:rw
      - ${CLONE_DIR}/venv:/ComfyUI/venv:rw
      - ${CLONE_DIR}/workflows:/ComfyUI/user/default/workflows:rw
    command: python /app/download_models.py
    working_dir: /ComfyUI
