custom_nodes:
  - name: comfyui-Core-vae
    repository: 
    version:
    type:  Core
    install_path: 
    models:
      - url: https://huggingface.co/mbrhan/sdxl-vae-fp16-fix/resolve/main/diffusion_pytorch_model.safetensors
        path: models/vae/sdxl_vae_fp16_fix.safetensors
  - name: comfyui-Core-LCM_lora
    repository: 
    version:
    type:  Core
    install_path: 
    models:
      - url: https://huggingface.co/Linaqruf/lcm-lora-sdxl-rank1/resolve/main/pytorch_lora_weights.safetensors
        path: models/loras/sdxl_LCM_lora_rank1.safetensors
  - name: comfyui_controlnet_aux
    repository: https://github.com/pictorialink/ComfyUI-controlnet_aux.git
    version: 5a049bde9cc117dafc327cded156459289097ea1 # Specific commit hash
    type: Community
    install_path: custom_nodes/ComfyUI-controlnet_aux
    models:
      - url: https://huggingface.co/lllyasviel/Annotators
        path: custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
      - url: https://huggingface.co/depth-anything/Depth-Anything-V2-Large/resolve/main/depth_anything_v2_vitl.pth
        path: custom_nodes/ComfyUI-controlnet_aux/ckpts/depth-anything/Depth-Anything-V2-Large/depth_anything_v2_vitl.pth
      - url: https://huggingface.co/yzd-v/DWPose/resolve/main/yolox_l.onnx
        path: custom_nodes/ComfyUI-controlnet_aux/ckpts/yzd-v/DWPose/yolox_l.onnx
